# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cdKjfX5qllGzyUDW4jTA3H0cMhG68ax1
"""

import streamlit as st
import pandas as pd
import openai
import json

st.set_page_config(page_title="Análise de Transbordos", layout="centered")

# Interface
st.title("🔍 Análise de Transbordos do Chatbot")
st.markdown("Envie uma base com **Assunto** e **Quantidade** de transbordos para análise.")

# API Key
api_key = st.text_input("🔐 Chave da OpenAI (sk-...)", type="password")
if api_key:
    openai.api_key = api_key

# Upload do arquivo
arquivo = st.file_uploader("📁 Envie um arquivo CSV", type="csv")

if arquivo and api_key:
    df = pd.read_csv(arquivo)

    st.subheader("👀 Visualização dos dados")
    st.dataframe(df)

    # Geração do prompt com base completa
    dados = df.to_dict(orient="records")
    dados_formatados = json.dumps(dados, indent=2, ensure_ascii=False)

    prompt = f"""
Você é um especialista em análise de chatbot. Abaixo estão os dados com assuntos e quantidades de transbordos registrados no chatbot.

Dados:
{dados_formatados}

Tarefa:
- Liste os assuntos com maiores volumes de transbordos.
- Identifique tendências ao longo dos meses, se houver.
- Aponte possíveis causas para os assuntos mais críticos.
- Sugira melhorias para reduzir os transbordos e melhorar a experiência do usuário.

Retorne a análise de forma clara, objetiva e com recomendações práticas.
    """

    with st.spinner("Analisando os dados..."):
        try:
            response = openai.chat.completions.create(
                model="gpt-4",
                messages=[
                    {"role": "system", "content": "Você é um especialista em análise de chatbot."},
                    {"role": "user", "content": prompt}
                ]
            )
            resultado = response.choices[0].message.content
            st.subheader("📊 Resultado da Análise")
            st.markdown(resultado)

        except Exception as e:
            st.error(f"Erro ao chamar a API: {e}")
else:
    st.info("Para começar, adicione sua chave da OpenAI e envie um arquivo CSV.")